version: '3.9'

services:
  astro-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./data:/app/data # SQLite база сохраняется вне контейнера
    environment:
      - NODE_ENV=production
    command: npm run preview
